FROM python:3.12-slim

# Install the Confluent Python client
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Copy in the producer code
COPY producer2.py /app/producer.py
COPY test.py /app/test.py
COPY test_vanilla.py /app/test_vanilla.py

# Run the Python script
CMD ["python", "/app/test_vanilla.py"]