services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    build:
      context: ./broker
    container_name: kafka-broker
    cap_add:
      - NET_ADMIN  # Allows modifying network settings
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Rely on Docker's internal network; to connect from other containers, use "kafka:9092"
    depends_on:
      - zookeeper
    command: ["/bin/sh", "-c", "/kafka/bin/kafka-server-start.sh /kafka/config/server.properties"]

  producer1:
    build:
      context: ./producer1
    container_name: kafka-producer-1
    cap_add:
      - NET_ADMIN  # Allows modifying network settings
    privileged: true
    depends_on:
      - kafka

  # producer2:
  #   build:
  #     context: ./producer2
  #   container_name: kafka-producer-2
  #   depends_on:
  #     - kafka
